### ISSUE TITLE
HttpClient does not respect IDisposable

### ISSUE THREAD

**Issue by IsaaacD** [d4n3436/GScraper#2]
Hello,

As per this article from Microsoft https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines `HttpClient` does not respect the `IDisposable` interface. If this is used in Asp.Net it could lead to socket exhaustion from too many connections.

Basically the Scraper classes shouldn't implement `IDisposable` and dispose of the `HttpClient`, this is from the article listed above:
>Any reasonably limited number of [HttpClient](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) instances will work as well. What matters here is that they are not created and disposed with each request as they each contain a connection pool. Using more than one instance is necessary for scenarios with multiple proxies or to separate cookie containers without completely disabling cookie handling. 

Would you be open to a PR that would also add some interfaces to better use/register classes in ASP.net dependency injection container and removes this interface?

Here's some additional reading on how it's used in ASP.net =>https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0#named-clients

**Comment by d4n3436** [comment]
The scraper classes are properly implemented, you have to inject them as transient services and retrieve the `HttpClient` instance from the `IHttpClientFactory`.

Ideally you should be able to register them as typed clients with `AddHttpClient`, but it's a bit tricky to do it because of the way I initially designed the library, since the scrapers have a constructor that takes a `HttpClient` instance and an API endpoint string, the dependency injection system gets confused as it cannot decide which constructor to use.

A solution for this is to add a named client for each scraper and then register the scrapers as transient with a factory that retrieves the correct `HttpClient` instance from the service provider.

Example:

```cs
services.AddHttpClient(nameof(Scraper));
services.AddTransient(s => new Scraper(s.GetRequiredService<IHttpClientFactory>().CreateClient(nameof(Scraper))));
```

Adding the scraper like this will ensure the inner `HttpClient` will be managed and disposed by the `IHttpClientFactory`.

**Comment by IsaaacD** [comment]
Oh okay, I didn't realize explicitly instanced objects in the DI pipeline didn't get disposed of. https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#services-not-created-by-the-service-container

Thanks for your response, I'll implement it as such.

**Comment by d4n3436** [comment]
I didn't mention explicitly instanced objects on my response, the scrapers are not meant to be used as singletons, but rather as transient services and created via factory methods like the example.

**Comment by IsaaacD** [comment]
Yea, in the article I linked in my last comment. If you register it like you're showing:

>services.AddTransient(s => new Scraper(s.GetRequiredService<IHttpClientFactory>().CreateClient(nameof(Scraper))));

Instead of:
```
services.AddHttpClient<Scraper>();
services.AddTransient<Scraper>();
```
Which would implicitly be calling the constructor with the most parameters it can resolve, aka the one with HttpProvider. Adding it this way I've shown will get the Scraper.Dispose() method called, and can lead to socket exhaustion.

From my initial post url:
>HttpClient instances can generally be treated as .NET objects not requiring disposal. Disposal cancels outgoing requests and guarantees the given HttpClient instance can't be used after calling Dispose. IHttpClientFactory tracks and disposes resources used by HttpClient instances
